---
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      DOMAIN_NAME:
        description: 'URL domain passed from Jenkins'
        required: true
        type: string
      STORE_NAME:
        description: 'Transact store name passed from Jenkins'
        required: true
        type: string
      STORE_TYPE:
        description: 'Transact store type passed from Jenkins'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
    - name: Set up JDK 8
      uses: actions/setup-java@8764a52df183aa0ccea74521dfd9d506ffc7a19a # v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        REPO_SERVER: ${{ secrets.REPO_SERVER }}
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        DEPLOY_DOMAIN: ${{ github.event.inputs.DOMAIN_NAME }}
        DEPLOY_STORENAME: ${{ github.event.inputs.STORE_NAME }}
        DEPLOY_STORETYPE: ${{ github.event.inputs.STORE_TYPE }}
      run: |
        mvn -ntp package -Dwebservices.base="$DEPLOY_DOMAIN" -Dtransact.type="$DEPLOY_STORETYPE" -Dtransact.store="$DEPLOY_STORENAME" -Dusername="$REPO_USERNAME" -Dpassword="$REPO_TOKEN"
    - name: Deploy with Jenkins
      env:
        CI_WS_SSH_PRIV_KEY: ${{ secrets.CI_WS_SSH_PRIV_KEY }}
        CI_JENKINS_DEPLOY_TOKEN: ${{ secrets.CI_JENKINS_DEPLOY_TOKEN }}
        CI_JENKINS_JOB_URI: ${{ secrets.CI_JENKINS_JOB_URI }}
        CI_JENKINS_TOMCAT_HOST: ${{ secrets.CI_JENKINS_TOMCAT_HOST }}
        CI_JENKINS_USER_CREDS: ${{ secrets.CI_JENKINS_USER_CREDS }}
        CI_WEBAPP_NAME: ${{ secrets.CI_WEBAPP_NAME }}
      run: sh scripts/deploy.sh
